version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:8888"
    environment:
      - FLASK_DEBUG=True
      - DYNAMODB_TABLE=my-dynamodb-table
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=password
