"""add answers

Revision ID: 09438b37330c
Revises: dc1249da172d
Create Date: 2024-12-01 17:46:22.240748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09438b37330c'
down_revision = 'dc1249da172d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('running_session_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    # ### end Alembic commands ###
