"""add susceptibility score to user

Revision ID: 1d27f6297a3a
Revises: 3e5ce0062ce4
Create Date: 2024-12-07 10:29:03.963127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d27f6297a3a'
down_revision = '3e5ce0062ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('susceptibility_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('susceptibility_score')

    # ### end Alembic commands ###
