"""add fields to question

Revision ID: 3e5ce0062ce4
Revises: 57068d17658e
Create Date: 2024-12-07 09:49:32.920291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5ce0062ce4'
down_revision = '57068d17658e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_summable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('is_summable')
        batch_op.drop_column('max_score')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
