"""add sort key

Revision ID: 52843c5d4aa3
Revises: 7bbc54e9969f
Create Date: 2024-12-01 16:52:39.057372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52843c5d4aa3'
down_revision = '7bbc54e9969f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('sort_index')

    # ### end Alembic commands ###
