"""refactor answers to option

Revision ID: 57068d17658e
Revises: 09438b37330c
Create Date: 2024-12-02 15:42:49.063289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57068d17658e'
down_revision = '09438b37330c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'options', ['option_id'], ['id'])
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('option_id')

    # ### end Alembic commands ###
