name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e_testing:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RUNNING_SESSIONS_DATA_TABLE: ${{ secrets.RUNNING_SESSIONS_DATA_TABLE }}
      RUNNING_SESSIONS_TABLE: ${{ secrets.RUNNING_SESSIONS_TABLE }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: make test